---
functional:
  - На сайте можно зарегистрироваться
  - При успешной регистрации на почту приходит письмо с подтверждением
  - При закрытии вкладки с сайтом авторизаци сохраняется
  - Пользователь может создать игру с ботом
  - Пользователь может создать игру с другом
  - Пользователь может создать игру с другим пользователем
  - Пользователь может прекратить игру с помощью кнопки "Give up"
  - На сайте можно авторизоваться через Git
  - На сайте можно авторизоваться через Discord
  - Имеется уведомление об успешно выполненном входе на сайт
  - Все элементы таблицы выровнены посередине в разделе My setings
  - Работает смена юзернейма в разделе Settings
  - Работает выбор количества пользователей на странице в User rating
  - При поиске по имени в User rating число в Total entries соответствует количеству строк результата поиска
  - Стрелки перелистывания страниц в User rating выполнены в одном стиле
non-functional:
  - Сайт должн быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным  на мобильном устройстве
  - Сайт должен быть совместимым с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновремнных пользователей)
inplicit:
  - 
